### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by prsn** [redux-offline/queue#1]
Hi @sorodrigo ,
Please confirm my understanding.
Every **ACTION** send to the queue will have a **method** property, which will have a side effect over the existing items in the `queue` or a CREATE method to augment the queue. The side effect depends on the description as specified [here](https://github.com/redux-offline/queue/blob/master/smart-queue/README.md#side-effects).

I have understood the point 1, 2, and 4, but a bit confused about point 3. The outcome of point 3 is `Replace UPDATE action with DELETE`, is it **recursive**? I mean, let's say, I have a CREATE action, which followed by an UPDATE action (outcome at this point is `merge` as specified in point 1), now if a DELETE request comes for the same resource, then the original method (CREATE) will be removed or it will be revert back to original CREATE method? Can you please explain point 3 a bit.

The side effect entire depends on the **identity** function, as we need to uniquely identify each action in the queue. An application will never know about this identity function, it is for internal operation of the queue. So, the hardest part is to devise identity function from the **ACTION** itself. Is my understanding correct?

Let me spend some time with identity function, I will share with you my thoughts/process to identify the action. If you have any thoughts on this, please let me know.

**Comment by sorodrigo** [comment]
Ok so first to clarify scenario 3. All actions will be enqueued and dequeued sequentially. This means that you should always have only one action with the same identifier at the same time. 
So if there’s a CREATE action, followed by an UPDATE. The UPDATE action will be merged into the CREATE action. Afterwards if this is followed by a DELETE, the scenario to apply here is scenario 2. Remove the CREATE action.

About the identity action, I think that making a fn that works for every case is nearly impossible. I would recommend using a key provided by the user. This is how React those it and works great!

**Comment by prsn** [comment]
Thanks for the reply @sorodrigo , scenario 3 behavior quite clear now.

About the identity fn. Yes using `key` is the best and safe way to identify any `ACTION`, but as per the initial considerations "the app won't know the id of the resource", are we not imposing a restriction on the app to provide a key (I am assuming that the `user` that you mentioned in the above comment and `app` is same)?

What if the user doesn't provide any `key`? Should we try to generate the `key` in this scenario?
I was thinking about finding `hashCode` of the request body (it's an expensive operation though).

Let me know your thought on this.

**Comment by sorodrigo** [comment]
I think the user (the developer using this plugin) should always provide a key and a method i.e.
```js
{
  type: ‘ADD_TODO’,
  payload: { description: ‘add docs’ },
  meta: {
    offline: {
      effect: ...,
      commit: ...,
      queue: {
        method: ‘CREATE’,
        key: ‘ADD_TODO_add_docs’
      }
    }
  }
}
```
The API doesn’t have to be exactly like this, but I think this ilustrates what I had in mind.

**Comment by prsn** [comment]
Alright, thanks for the input.
So the assumption is that user will always provide `key` and `method`. This will definitely make the whole algorithm quite simple.

By any changes, if the user doesn't provide either of `key` or `method` OR both, then shall we just perform normal queue operation or we will ignore that action with a warning message?

Let me know your thought on this.

**Comment by sorodrigo** [comment]
Good question! I think ignoring normally and ignoring with a warning if one of the two options is missing.

**Comment by prsn** [comment]
Thanks for the input @sorodrigo.
Will create PR with required behavior soon.

**Comment by prsn** [comment]
Hi @sorodrigo ,
While writing the code and the test cases, I came across a situation about point 4 (`READ action -> READ action ->> Squash READ actions into a single action.`).

Can you please explain READ operation?

I am facing problem in understanding `READ` action w.r.t `enqueue`, what `smart-queue` will do if very first action is `READ`?

Another question, what if 2 `CREATE` actions are `enqueued` with the same key, it is possible?

**Comment by sorodrigo** [comment]
> Another question, what if 2 CREATE actions are enqueued with the same key, it is possible?

I think it shouldn't be possible and if it happened we shouldn't apply any special considerations.

> Can you please explain READ operation?

I was thinking of a request for a resource. For example:
```js
const headers = { Authorization: 'fsghjkx87e8qwbsdjy9bhj' };
{
  type: GET_USER_REQUEST,
  meta: {
    offline: {
      effect: { url: `${BASE_API}/user`, headers },
      commit: { type: GET_USER_COMMIT },
      queue: {
        method: 'READ',
        key: GET_USER_REQUEST
      }
    }
  }
}
```
So basically we want to avoid requesting the same resource twice.

**Comment by prsn** [comment]
Thanks for the reply,
What have I understood is that, from `smart-queue` perspective, `READ` is just another queue action, right?
Or I am missing something?

**Comment by sorodrigo** [comment]
I don't follow, what do you mean by _just another queue action_?
What I meant to say is that if the outbox equals:
```js
offline.outbox = [
  { type: CREATE_TODO, meta: { offline: { ... } } },
  { type: GET_USER_REQUEST, meta: { offline { ..., queue: { ..., method: 'READ' } },
  { type: UPDATE_TODO, meta: { offline: { ... } } },
];
```
And afterwards `GET_USER_REQUEST` gets dispatched again, instead of having it twice inside the outbox:

```js
// UNWANTED BEHAVIOUR
offline.outbox = [
  { type: CREATE_TODO, meta: { offline: { ... } } },
  { type: GET_USER_REQUEST, meta: { offline { ..., queue: { ..., method: 'READ' } },
  { type: UPDATE_TODO, meta: { offline: { ... } } },
  { type: GET_USER_REQUEST, meta: { offline { ..., queue: { ..., method: 'READ' } },
];
```

We would preserve only one of the entries:
```js
// EXPECTED BEHAVIOUR
offline.outbox = [
  { type: CREATE_TODO, meta: { offline: { ... } } },
  { type: GET_USER_REQUEST, meta: { offline { ..., queue: { ..., method: 'READ' } },
  { type: UPDATE_TODO, meta: { offline: { ... } } }
];
```

**Comment by prsn** [comment]
Yes, we are on the same page, for the same action key, two READ requests will always be merged.
I just wanted to say that, how 'READ' action will be used (outside queue) is irrelevant to `smart-queue`. `smart-queue` will always treat action as per queue configuration (`queue:{..., method:}`, which you have already specified).

Current implementation always merges 2 `READ` actions if they share the same key.
