### ISSUE TITLE
Renaming repo

### ISSUE THREAD

**Issue by sorodrigo** [redux-offline/queue#3]
Hey @wacii @piranna I created this repo so @prsn could have somewhere to work. He’s been developing with a little help of mine a redux-offline plugin that will add smart behavior to the queue. He’s almost done with it a looks pretty awesome.

With that in mind, I was thinking that this repo could hold not only queue but other plugins too, so maybe its better to rename it?

**Comment by piranna** [comment]
Good idea :-) Although if you plan to do some other plugins, is better to have them in their own repos. Regarding name, what about `redux-offline-plugin-queue`? This way it would be easy to search on npm...

**Comment by sorodrigo** [comment]
I was thinking in a `redux-plugin` mono repo kinda like babel

**Comment by wacii** [comment]
Interesting. I have no experience with mono repos, but they seem to work for people. Familiar with Lerna?

**Comment by piranna** [comment]
I personally don't like monorepos, it's more difficult to find the source code you are looking on them... I find it much better to have minimal, standalone projects.

**Comment by sorodrigo** [comment]
I wouldn’t worry about finding the code. We want plugins to be simpler. I think being able to maintain one single dev environment (eslint, babel, prettier, whatevs) in a project we shouldn’t spend that much time is way better than maintaining several smaller projects.

**Comment by piranna** [comment]
Having several smaller projects would help third-parties to use them as basis to develop their own ones...

**Comment by sorodrigo** [comment]
moving to https://github.com/redux-offline/tools
