### ISSUE TITLE
Smart Queue Merging is Incorrect

### ISSUE THREAD

**Issue by calumpeak** [redux-offline/queue#4]
Hi @sorodrigo, @prsn 

I took the smart queue out for a small spin, just with the CREATE and UPDATE actions and noticed that we are merging actions incorrectly.

Here's what I've noticed initially:
1) New actions payloads don't get merged into queuedActions
2) New actions overwrite the meta.offline payload entirely. This replaces any effect/commit/rollback actions a user may have on the original action. E.g. Create is replaced with the Update meta - for any backend this is impossible once we try to resolve this action as you can't update an entity that isn't created. We shouldn't touch the original actions offline.meta when merging actions unless they're being removed/replaced from the queue
3) Update actions should be able to merge on top of Update actions, only merges over Create currently and gets ignored.
3) For cases where `index` is false, we just return the outbox array. This means the action that doesn't match anything we ignore it...We should be adding it to the outbox queue `[...array, action]` by default.
4) Regarding Delete:
   -  If key matches Update, Delete should replace it (It's already been created as far as an API is concerned, else if it was squashed it would be a Create action)
   - If key matches Create we just remove Create (as we currently do now)

Thoughts?

P.S. I'd be more than happy to update this.

**Comment by sorodrigo** [comment]
I agree with `points 1, 3, 5` (point 3 was my bad I made a mistake of specifying that behaviour on the original design).

Regarding `point 4` I can't find the case where this happens. We ignore it when an action with the same key exists in the outbox.

About `point 2` I agree that we shouldn't loose the original `effect, commit, rollback` but what happens when you define commit and rollback meta that depends on your action? I think we should mergeDeep in some way so that we don't loose original meta but we update the meta that needs to be updated.

If we take as a convention, merging `offline.meta` deeply users might be able to code thinking on this. But I'm not 100% sold so if you think there's a better way lets discuss it.

What do you think? @prsn 

Thanks a lot for going through this! I could use some help to review and add the changes you suggested. I'm swamped between this, redux-offline core, other projects, work and a course I'm writing so I haven't been able to properly test this.

**Comment by calumpeak** [comment]
Regarding `point 4`, if the action has `queue` attribute, `index === -1`, and has any other method apart from `CREATE/READ` then there is no statement to catch that action to add it to the queue as it won't meet the predicate of the checks in the switch statement. At best, all that happens is a default `return queue`

`Point 2` Merging is quite awkward depending on if the user is either using the default `effect` or not. If Default does the user send the entire payload in the update patch? In which case you can replace the `body` of effect. If they don't send (e.g. they only send updates for the bits of data that need updating) the whole lot then you need to deserialise body -> merge -> stringify. If not default `effect`, do we give the user a way to handle custom merges? For instance the custom effect implementation we use just pulls the data out of the payload and sends that for the request so that we don't need duplicate data in body. (do we even want to code for custom effect implementations?)
The `effect.url` field should remain unchanged from `CREATE` -> `UPDATE`/ `UPDATE` -> `UPDATE` merging. Commit/Rollback should leave default `type` on merging, additional fields may want to be merged.

**Comment by sorodrigo** [comment]
Ok so regarding `point 2` I gave it  a little thought and my conclusion is that we should set some kind of convention for the data merging. We could decide to support or don't support default effect (I don't mind if we don't) and just document a property inside the effect and rest of `meta.offline` keys a way to merge the data.

For example:

**Create todo**
```js
// create
const userId = getState().user.id;
const todo = { text: 'Do homework', date: 1531170064607 };
return {
  type: CREATE_TODO,
  payload: todo,
  meta: {
    offline: {
      effect: {
        url: 'my-api/todo',
        method: 'POST',
        body: todo
      },
      commit: {
        type: CREATE_TODO_COMMIT,
        meta: { body: { userId } }
      },
      rollback: {
        type: CREATE_TODO_ROLLBACK,
        meta: { body: { ...todo, draft: true } }
      },
      queue: { method: 'CREATE', key: todo.date }
    }
  }
};
```

**Update todo**
```js
const userId = getState().user.id;
const todo = getState().todos[selectedId];
const newTodo = { ...todo, text: 'Do homework and laundry' };
return {
  type: UPDATE_TODO,
  payload: newTodo,
  meta: {
    offline: {
      effect: {
        url: 'my-api/todo',
        method: 'PATCH',
        body: newTodo
      },
      commit: {
        type: UPDATE_TODO_COMMIT,
        meta: { body: { userId } }
      },
      rollback: {
        type: UPDATE_TODO_ROLLBACK,
        meta: { body: { ...newTodo } }
      },
      queue: { method: 'UPDATE', key: newTodo.date }
    }
  }
};
```

**Merging strategy**
```js
const createAction = outbox[2];
const updateAction = outbox[5];
const createMetaOffline = createAction.meta.offline;
const updateMetaOffline = updateAction.meta.offline;

const mergedAction = {
  ...createAction,
  payload: { ...createAction.payload, ...updateAction.payload },
  meta: {
    offline: {
      ...createMetaOffline,
      effect: {
        ...createMetaOffline.effect,
        body: updateMetaOffline.body
      },
      commit: {
        ...createMetaOffline.commit,
        meta: {
          ...createMetaOffline.commit.meta,
          body: updateMetaOffline.commit.meta.body // *
        }
      },
      rollback: {
        ...createMetaOffline.rollback,
        meta: {
          ...createMetaOffline.rollback.meta,
          body: updateMetaOffline.rollback.meta.body
        }
      }
    }
  }
};
```
**\* the merge at commit/rollback meta.body could be done merging or squashing. SEE BELOW**
```js
{
  ...createMetaOffline.commit.meta,
  body: {
    ...createMetaOffline.commit.meta.body,
    ...updateMetaOffline.commit.meta.body
  }
};
```

I used `body` cause this ~kinda not really~ works with the default effect but we don't have to call it that. Like always, if you see something wrong or have a better solution I'm open to discussing it, I prefer taking longer to release and having a sound implementation. 😄

**Comment by calumpeak** [comment]
I like, and I think it's more on the right lines of what we're trying to achieve. 
I think it also might be a good idea to allow the user to pass their own custom merge function via a config also (if they want the ability of deep merging or being more specific if they have custom effects etc). Regarding the default effect, should we be parsing/stringifying `body` for the user also?

I'll take a look at drafting some of this up when I get a minute.

**Comment by calumpeak** [comment]
^Woops, misclick

**Comment by prsn** [comment]
Hi @sorodrigo , @echoes221 

Sorry for the delayed response.
I do support the idea that @echoes221 has suggested, along with the `default merger` we can also consider the `custom merger`. What I feel is that the `merging` to some extends depends on the `users` also.

 Regarding `point 4`, the `DELETE/UPDATE` action has a dependency over the existing action, When `index === -1`, I don't see any reason to add that action into the queue. The case where this scenario can occur is when the corresponding `CREATE/UPDATE` action has been processed, in that case, `DELETE/UPDATE` is just becoming void. Another case could be when the `user` set the wrong keys.

Regarding `point 3`, In one of the initial PR review `Wacci` has already pointed out this issue and I also strongly believe that we should allow `UPDATE` over `UPDATE`.

Regarding `point 5`, It's a good idea to replace `UPDATE` with `CREATE` action upon `DELETE`, but what if the user wants to actually delete the `UPDATE` action. In this case, the user has to initiate 2 `DELETE` actions to actually delete an `UPDATE` action, the path will be like `CREATE->UPDATE->DELETE (UPDATE will replace with CREATE)->DELETE`.  any thoughts @sorodrigo @echoes221 .

**Comment by calumpeak** [comment]
Welcome back @prsn  :smile:

For this convo's context when I say entity, I mean a piece of data that has a unique identifier in an application/back end service. For example in the snippet below, the entities are `123` and `456` (which would also be `key` in the context of smart-queue).

```javascript
const todos = {
  123: {
    text: 'foo'
  },
  456: {
    text: 'bar'
  }
}
```

I agree that merging is specific to the user, so supporting custom mergers is important, especially considering the various `effect` implementations users have. By default I believe we should support `redux-offline`'s default `effect` and go from there. 

Coming back to `point 4` it depends on what network connectivity state a user has submitted an action under. Remember that `redux-offline` works optimistically. The DB at the other end of the API is the source of truth at the end of the day. For example: If a user is online and `CREATE`s an entity then goes offline and `DELETE`s it then we need to ensure that action correctly propagates when a user comes back online so their API is updated (the queue will potentially be empty when the user goes offline, so there will be no items to match with). Else we get into a state where the DB has the entity and the user thinks it's deleted as per their UI view (as the `DELETE` action has already been handled optimistically in the reducer). 

This is why I believe if the user has set a `method` and a `key` but we don't match an action in the `outbox` then it should just be added to the `outbox` by default - we don't know the state of the users application/DB. Though we should always assume that a user will be coming in and out of network connectivity and the `outbox` queue is not always the source of truth, it's only a source of truth when a user is __offline__, if a user is online then it's going to be empty unless processing an action, and we have no record of what happened prior to the user going offline.

`Point 3` :+1:, I think we're all agreed that we should update the updates.

`Point 5` I think there is a little confusion around `DELETE`, I'll explain from my perspective to see if that help makes sense of it, though I may be off the mark with this. The smart queue should be adhering to DB and REST principles. Actions that propagate through the `outbox` are to do with entities that live in the back end somewhere. If you're `UPDATE`ing, you're updating an entity. If you dispatch a `DELETE` it's not the `UPDATE` you're deleting, it's the entity itself (as mentioned above, this may be a scenario where the user has created the entity whilst online), therefore we should remove the `UPDATE` from the queue and replace it with `DELETE`. If a user is offline and has `CREATE` -> `UPDATE` (stays as `CREATE` due to squashing) -> `DELETE` then we can just remove `CREATE` from the `outbox` as, from the back ends point of view, that entity was never created in the first place. 
In these scenarios I can't see why you'd need to initiate multiple `DELETE` actions, we shouldn't be aiming to `DELETE` an `UPDATE`, but removing the entity itself.

**Comment by prsn** [comment]
Thanks for the example @echoes221  :),

Let me explain my perspective towards `Smart-Queue`. First of all `Smart-Queue` actions (`CREATE/UPDATE/DELETE`) are not the same as `HTTP` actions (`UPDATE/DELETE/...`). `Smart-Queue` actions are just to manage the `actions` within the `smart-queue` only. @sorodrigo please correct me if I am wrong.

Coming back to your example, if the user is **online** and `CREAT`'s an entity (this will be `smart-queue` `CREATE` action) and then goes **offline** and `DELETE` that entity (I guess you want to indicates the `HTTP DELETE` method), in this case, they will initiate `smart-queue`'s `CREATE` action where `effect` will have `method: DELETE`. So, this will create a new action within the `smart-queue` which will propagate once the user comes back to online.

Ex.:

```
{
  ...
  meta: {
    offline: {
      effect: {
        ...
        method: 'DELETE'
      }
      ...
      queue: { key: *some unique key*, method: 'CREATE' }
    }
  }
}
```

Can you please re-think on `point 4 & 5` considering the behaviour explained above and let us know your point of view.

**Comment by sorodrigo** [comment]
I think it makes sense to match our methods with http methods when possible. The alternative might be somewhat confusing.

My idea is the following:

- If both the `CREATE` and the `DELETE` exist in the outbox, we remove both actions cause the resource hasn't been created on the DB.

- If both the `UPDATE` and the `DELETE` exist in the outbox, we squash the `UPDATE` and only keep the `DELETE` action.

- If only the `DELETE` action exists in the outbox, I think we should keep it and have it perform the delete on the DB.

In general I agree with always adding the actions if `index === -1`.

**Comment by calumpeak** [comment]
@sorodrigo Sounds good. If we keep the methods inline with HTTP it clears things up for us and our users also - there shouldn't be any unexpected result. At the end of the day we're aiming for one decorated action per entity in the queue when the user is offline.

@prsn If a user is online when they CREATE (and it gets resolved) then they switch offline and `DELETE` then the queue should only contain `DELETE` as the outbox when the `DELETE` happened would be empty prior. 
I feel like Im missing something from your example, I don't understand why we'd reference different methods on actions. The outbox action doesn't need to keep a history, it should just be the method/action itself - we should avoid crossing over of methods on an action. We either replace the original, merge into the original (keeping the originals method and key), or remove the original.

**Comment by prsn** [comment]
Ah! I was in the different page :), now it makes sense to rectify the `DELETE` action. 

@echoes221, I had a different perspective. I do agree, it does things clear up if we align methods with HTTP.

**Comment by sorodrigo** [comment]
OK great!! We have consensus 😄.

**Comment by calumpeak** [comment]
Sounds good. I'll look at mocking something up when I get a minute 😄

**Comment by sorodrigo** [comment]
I created a mono repo at https://github.com/redux-offline/tools, let's continue working there!

**Comment by calumpeak** [comment]
Sweet. Lerna. I'm fairly familiar with it if you need a hand sorting anything out.
